# Generated by Django 5.1 on 2024-09-10 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('properties', '0004_property_latitude_property_longitude_nearbyplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('active_listings', models.ManyToManyField(blank=True, related_name='listed_by_agent', to='properties.property')),
                ('inquiry_listings', models.ManyToManyField(blank=True, related_name='inquired_by_agents', to='properties.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_properties', models.ManyToManyField(blank=True, related_name='favorited_by_customers', to='properties.property')),
                ('own_properties', models.ManyToManyField(blank=True, related_name='owned_by_customers', to='properties.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
